lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600 # token TTL in seconds, defaults to 1 hour

    encoder:
        service: lexik_jwt_authentication.encoder.lcobucci
        signature_algorithm: RS256

    token_extractors:
        # look for a token as Authorization Header
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization

        query_parameter:
            enabled: false
            name: bearer